.TH KSI-EXTEND 1
.\"
.\"
.\"
.SH NAME
\fBksi extend \fR- Guardtime command-line tool for extending KSI Signatures.
.\"
.\"
.SH SYNOPSIS
.\"
.HP 4
\fBksi extend -i \fIin.ksig \fR[\fB-o \fIout.ksig\fR] \fB-X \fIURL \fR[\fB--ext-user \fIuser \fB--ext-key \fIkey\fR] \fB-P \fIURL \fR[\fB--cnstr \fIoid\fR=\fIvalue\fR]... [\fImore options\fR]
.HP 4
\fBksi extend -i \fIin.ksig \fR[\fB-o \fIout.ksig\fR] \fB-X \fIURL \fR[\fB--ext-user \fIuser \fB--ext-key \fIkey\fR] \fB-P \fIURL \fR[\fB--cnstr \fIoid\fR=\fIvalue\fR]... \fB--pub-str \fIstr \fR[\fImore options\fR]
.HP 4
\fBksi extend -i \fIin.ksig \fR[\fB-o \fIout.ksig\fR] \fB-X \fIURL \fR[\fB--ext-user \fIuser \fB--ext-key \fIkey\fR] \fB-T \fItime \fR[\fImore options\fR]
.br
.\"
.\"
.SH DESCRIPTION
.\"
.HP 0
This is a KSI signature extending tool that can be used to extend the KSI signature to the time of a publication. After signature is extended and a publication record is attached it can be verified by publication-based verification where only trusted publications file or a copy of a printed media with corresponding publication string in it is needed to perform the verification (see \fBksi-verify\fR(1)\fR).
.HP 0
User must have an access to a KSI extending service and trusted KSI publications file, to be able to extend the KSI signature and link the publication record with it. By default signature is extended to the earliest available publication relative to the signing time. To extend to a specific publication from the publications file specify the publication string with option \fB--pub-str\fR. It is also possible to extend to the specified time with option \fB-T \fRbut this is not recommended as the extended signature will have no signature nor publication record thus can only be verified by calendar-based verification only. In that case publications file is not required.
.\"
.\"
.SH OPTIONS
.\"
.TP
\fB-i \fIdata\fR
KSI signature file to be extended. Use '-' as file name to read signatures file from \fIstdin\fR.
.\"
.TP
\fB-o \fIfile\fR
Output file name to store the extended signature token. Use '-' as file name to redirect signature binary stream to \fIstdout\fR. If not specified signature is saved to the path described as <input files path>_nr.ext, where \fInr\fR is generated sequential number if file name already exists. If specified will always overwrite the existing file.
.\"
.TP
\fB-X \fIURL\fR
Specify extending service URL.
.\"
.TP
\fB--ext-user \fIstr\fR
User name for extending service.
.\"
.TP
\fB--ext-key \fIstr\fR
HMAC Key for extending service.
.\"
.TP
\fB-P \fIURL\fR
Specify publications file URL (or file with URI scheme 'file://').
.\"
.TP
\fB--cnstr \fIoid\fR=\fIvalue\fR
OID and its expected value to verify publications file PKI signature. At least one constraint must be defined to be able to verify publications file but it is possible to define more. All values from lower priority source are ignored, where default configurations file is the lowest and command-line is the highest.
.\"
.TP
\fB--pub-str \fIstr\fR
Specify a publication record by its publication string to extend to.
.TP
\fB-T \fItime\fR
Specify a publication time to extend to as the number of seconds since 1970-01-01 00:00:00 UTC or time string formatted as "YYYY-MM-DD hh:mm:ss".
.\"
.TP
\fB-d\fR
Print detailed information about processes and errors to \fIstderr\fR.
.\"
.TP
\fB--conf \fIfile\fR
Specify a configurations file to override default service information. It must be noted that service info from command-line will override the configurations file. See \fBksi\fR(1) and \fBksi-conf\fR(5) for more information.
.\"
.TP
\fB--log \fIfile\fR
Write libksi log into file. Use '-' as file name to redirect log to \fIstdout\fR.
.br
.\"
.\"
.\"
.SH EXIT STATUS
See \fBksi\fR(1) for more information.
.\"
.\"
.\"
.SH EXAMPLES
.\"
In the following examples it is assumed that default service URLs are defined (see \fBksi\fR(1) \fRfor more information).
.\"
.TP 2
\fB1
\fRTo extend a signature \fIsig.ksig\fR to the earliest available publication and save it as \fIext.ksig\fR call:
.LP
.RS 4
.HP 4
\fBksi extend -i \fIsig.ksig \fB-o \fIext.ksig
.RE
.\"
.TP 2
\fB2
\fRTo extend a signature \fIsig.ksig\fR to s specified publication (Publication string available from Financial Times, ISSN: 0307-1766, 2016-03-17):
.LP
.RS 4
.HP 4
\fBksi extend -i \fIsig.ksig \fB-o \fIext.ksig \fB--pub-str \fIAAAAAA-CW45II-AAKWRK-F7FBNM-KB6FNV-DYYFW7-PJQN6F-JKZWBQ-3OQYZO-HCB7RA-YNYAGA-ODRL2V
.RE
.\"
.TP 2
\fB3
\fRTo extend a signature \fIsig.ksig\fR to specified calendar time \fI2015-05-05 00:00:00 \fRand save it as \fIext.ksig\fR call:
.LP
.RS 4
.HP 4
\fBksi extend -i \fIsig.ksig \fB-o \fIext.ksig \fB-T \fI"2015-05-05 00:00:00"
.RE
.LP
.\"
.\"
.\"
.SH ENVIRONMENT
Environment variable \fBKSI_CONF \fR can be defined to set default KSI configurations file. See \fBksi\fR(1) and \fBksi-conf\fR(5) for more information.

.SH AUTHOR

Guardtime AS, http://www.guardtime.com/

.SH SEE ALSO	
\fBksi\fR(1), \fBksi-sign\fR(1), \fBksi-verify\fR(1), \fBksi-pubfile\fR(1), \fBksi-conf\fR(5) 