.TH KSI-PUBFILE 1
.\"
.\"
.\"
.SH NAME
\fBksi pubfile \fR- Guardtime command-line tool for verifying and dumping KSI publications file.
.\"
.\"
.SH SYNOPSIS
.\"
.HP 4
\fBksi pubfile -P \fIURL \fB--dump\fR
.HP 4
\fBksi pubfile -P \fIURL \fB-o \fIpubfile.bin \fB--cnstr \fIoid\fR=\fIvalue \fR... \fR[\fB-V \fIcert.pem\fR]... \fR[\fB-W \fIdir\fR]... [\fImore options\fR]
.HP 4
\fBksi pubfile -P \fIURL \fB-v \fB--cnstr \fIoid\fR=\fIvalue \fR... \fR[\fB-V \fIcert.pem\fR]... \fR[\fB-W \fIdir\fR]... [\fImore options\fR]
.HP 4
\fBksi pubfile \fB-T \fItime\fR \fB-X \fIURL \fR[\fB--ext-user \fIuser \fB--ext-key \fIkey\fR] [\fImore options\fR]
.br
.\"
.\"
.SH DESCRIPTION
.\"
This is a KSI publications file tool for performing publications file related general tasks. 
.\"
.\"
.SH OPTIONS
.\"
.TP
\fB-P \fIURL\fR
Specify publications file URL (or file with URI scheme 'file://').
.\"
.TP
\fB--cnstr \fIoid\fR=\fIvalue\fR
OID and its expected value to verify publications file PKI signature. At least one constraint must be defined to be able to verify publications file but it is possible to define more. All values from lower priority source are ignored, where default configurations file is the lowest and command-line is the highest.
.\"
.TP
\fB-v\fR
Perform publications file verification. Note that when \fB-o \fRis used to save signatures file verification is always performed.
.\"
.TP
\fB-V \fIfile\fR
Specify an OpenSSL-style trust store file for publications file verification. All values from lower priority source are ignored, where default configurations file is the lowest and command-line is the highest.
.\"
.TP
\fB-W \fIdir\fR
Specify an OpenSSL-style trust store directory for publications file verification. All values from lower priority source are ignored, where default configurations file is the lowest and command-line is the highest.
.\"
.TP
\fB-o \fIfile\fR
Output file name to store publications file. Use '-' as file name to redirect publications file binary stream to \fIstdout\fR. Publications file is always verified before saving.
.\"
.TP
\fB-X \fIURL\fR
Specify extending service URL.
.\"
.TP
\fB--ext-user \fIstr\fR
User name for extending service.
.\"
.TP
\fB--ext-key \fIstr\fR
HMAC Key for extending service.
.\"
.TP
\fB-T \fItime\fR
Specify a time to create a publication string for as the number of seconds since 1970-01-01 00:00:00 UTC or time string formatted as "YYYY-MM-DD hh:mm:ss".
.\"
.TP
\fB-d\fR
Print detailed information about processes and errors to \fIstderr\fR.
.\"
.TP
\fB--dump\fR
Dump Publications file to \fIstdout\fR. Without any extra flags publications file verification is not performed.
.\"
.TP
\fB--conf \fIfile\fR
Specify a configurations file to override default service information. It must be noted that service info from command-line will override the configurations file. See \fBksi\fR(1) and \fBksi-conf\fR(5) for more information.
.\"
.TP
\fB--log \fIfile\fR
Write libksi log into file. Use '-' as file name to redirect log to \fIstdout\fR.
.br
.\"
.\"
.\"
.SH EXIT STATUS
See \fBksi\fR(1) for more information.
.\"
.\"
.\"
.SH EXAMPLES
.\"
In the following examples it is assumed that default service URLs are defined (see \fBksi\fR(1) \fRfor more information).


\fB1\fR To dump a publications file from default URL call:
.RS
\fBksi pubfile --dump
.RE

\fB2\fR To dump a publications file \fIpubfile.bin\fR from local disk call (verification is not performed):
.RS
\fBksi pubfile --dump -P \fIfile://pubfile.bin\fR
.RE

\fB3\fR To verify a publications file \fIpubfile.bin\fR from local disk call:
.RS
\fBksi pubfile -v -P \fIfile:///home/user/publications/pubfile.bin\fR
.RE

\fB4\fR To download and verify a publication file \fIpubfile.bin\fR call:
.RS
\fBksi pubfile -o \fIpubfile.bin\fR \fB--cnstr \fIemail=publications@guardtime.com
.RE

\fB5\fR To verify a publications file with only certificates defined on command-line call:
.RS
\fBksi pubfile -v -V \fIcertificate_1.bin \fB-V \fIcertificate_2.bin \fB--cnstr \fIemail=publications@guardtime.com
.RE

\fB6\fR To create a publication string call:
.RS
\fBksi pubfile -T \fR"\fI2015-10-15 00:00:00\fR" 
.RE



.\"
.\"
.\"
.SH ENVIRONMENT
Environment variable \fBKSI_CONF \fR can be defined to set default KSI configurations file. See \fBksi\fR(1) and \fBksi-conf\fR(5) for more information.

.SH AUTHOR

Guardtime AS, http://www.guardtime.com/

.SH SEE ALSO	
\fBksi\fR(1), \fBksi-sign\fR(1), \fBksi-verify\fR(1), \fBksi-extend\fR(1), \fBksi-conf\fR(5) 