.TH KSI 1
.\"
.SH NAME
\fBksi \fR- Keyless Signature Infrastructure (KSI) command-line tool, also called KSI tool.
.\"
.SH SYNOPSIS
\fBksi \fR[\fB-h\fR][\fB--version\fR]
.br
\fBksi \fBcommand\fR \fB-h\fR
.br
\fBksi \fBcommand\fR [\fIservice_parameters\fR][\fIoptions\fR]
.\"
.SH DESCRIPTION
Keyless Signature Infrastructure (KSI) is an industrial scale blockchain platform that cryptographically ensures data integrity and proves time of existence. Its keyless signatures, based on hash chains, link data to global calendar blockchain.
.LP
KSI command-line tool enables the access to the KSI blockchain and its functions from the shell. It can be used for signing data in files or other sources, extending existing KSI signatures and verifying them using different trust anchors. The first argument of the tool is the KSI command followed by the KSI service configuration parameters and options.
.LP
See \fBksi-conf\fR(5) or man page of specific KSI command for more information about KSI service configuration.
.LP
.SH KSI COMMANDS
.LP
.TP
\fBsign\fR
Signs the given input with KSI. See \fBksi-sign\fR(1) for more information.
.\"
.TP
\fBverify\fR
Verifies existing KSI signature. See \fBksi-verify\fR(1) for more information.
.\"
.TP
\fBextend\fR
Extends existing KSI signature to the given publication. See \fBksi-extend\fR(1) for more information.
.\"
.TP
\fBpubfile\fR
Downloads and verifies KSI publications file. See \fBksi-pubfile\fR(1) for more information.
.\"
.SH OPTIONS
.\"
.TP
\fB-h\fR
Print help text. Use \fBksi command -h\fR to print help for the specific command.
.\"
.TP
\fB--version\fR
Print version info.
.\"
.\"
.SH EXIT STATUS
.TP
\fB0\fR
\fBExit success.\fR Returned if everything is OK.
.\"
.TP
\fB1
\fBExit failure.\fR A general failure occurred.
.\"
.TP
\fB3
\fBInvalid command-line parameter.\fR The content or format of a command-line parameter is invalid or a parameter is missing.
.\"
.TP
\fB4
\fBInvalid format.\fR Input data to KSI library is invalid, for example signature or publication file format is invalid.
.\"
.TP
\fB5
\fBNetwork error.\fR KSI tool is unable to connect to the service, connection is timed out or an HTTP error was returned from the KSI service.
.\"
.TP
\fB6
\fBVerification error.\fR Verification of signature or document hash failed.
.\"
.TP
\fB7
\fBExtending error.\fR Error in extending a signature or an error was returned by KSI Extender.
.\"
.TP
\fB8
\fBAggregation error.\fR Error returned by KSI Aggregator.
.\"
.TP
\fB9
\fBInput / output error.\fR Unable to read or write file.
.\"
.TP
\fB10
\fBCryptographic error.\fR Error may be generated due to mistrusted or unavailable hash algorithm or by an invalid PKI signature / mistrusted certificate.
.\"
.TP
\fB11
\fBHMAC error.\fR HMAC of aggregation or extend response does not match.
.\"
.TP
\fB12
\fBNo privileges.\fR Operating system did not grant privileges to perform an operation.
.\"
.TP
\fB13
\fBSystem out of memory.\fR
.\"
.TP
\fB14
\fBAuthentication error.\fR KSI Aggregation or Extending service did not accept the provided access credentials.
.br
.\"
.TP
\fB16
\fBInvalid configuration.\fR KSI tool configuration or KSI C API library configuration is invalid.
.br
.\"
.SH ENVIRONMENT
The \fBKSI_CONF\fR environment variable points to the KSI configuration file containing the KSI service related parameters such as the URLs to the KSI Aggregator and Extender service and the corresponding access credentials. See \fBksi-conf\fR(5) for more information.
.LP
.\"
.SH AUTHOR
Guardtime AS, http://www.guardtime.com/
.LP
.\"
.SH SEE ALSO
\fBksi-sign\fR(1), \fBksi-verify\fR(1), \fBksi-extend\fR(1), \fBksi-pubfile\fR(1), \fBksi-conf\fR(5) 
