.TH KSI 1
.\"
.\"
.\"
.SH NAME
\fBksi \fR- Guardtime command-line tool for KSI (Keyless Signature Infrastructure)service.
.\"
.\"
.SH SYNOPSIS
.\"
.br
\fBksi \fR[\fB-h\fR] [\fB--version\fR] [\fImore options\fR]
.br
\fBksi \fIcomponent \fR[\fB-h\fR] [\fIservice info\fR] [\fImore options\fR]
.\"
.\"
.SH DESCRIPTION
.\"
This is a general signing and signature verification tool for Guardtime Keyless Signature services.
.\"
.\"
.SH OPTIONS
.\"
.TP
\fB-h\fR
Print help text of program ksi. To print a help text of ksi component use \fB-h\fR with specified component name.
.\"
.TP
\fB--version\fR
Print version info.
.\"
.\"
.SH KSI COMPONENTS
.\"

.TP
\fBsign\fR
KSI general signing tool. See \fBksi-sign\fR(1) for more information.
.\"
.TP
\fBverify\fR
KSI signing verification tool. See \fBksi-verify\fR(1) for more information.
.\"
.TP
\fBextend\fR
KSI signing extending tool. See \fBksi-extend\fR(1) for more information.
.\"
.TP
\fBpubfile\fR
KSI general publications file verification tool. See \fBksi-pubfile\fR(1) for more information.
.\"

.SH EXIT STATUS
.TP
\fB0\fR
\fBExit success.\fR Returned if everything is OK.
.\"
.TP
\fB1
\fBExit failure.\fR A general failure occurred.
.\"
.TP
\fB3
\fBInvalid command-line parameter.\fR The content or format of command-line parameter is invalid. Also a parameter may be missing.
.\"
.TP
\fB4
\fBInvalid format.\fR Input data to KSI library is invalid, for example signature or publication file format is invalid.
.\"
.TP
\fB5
\fBNetwork error.\fR Ksitool is unable to connect to the service, connection is timed out or an HTTP error was returned from the service url.
.\"
.TP
\fB6
\fBVerification error.\fR Verification of signature or document hash failed.
.\"
.TP
\fB7
\fBExtending error.\fR Error in extending a signature or an error was returned by extender.
.\"
.TP
\fB8
\fBAggregation error.\fR Error returned by aggregator.
.\"
.TP
\fB9
\fBInput / output error.\fR Unable to write or read file.
.\"
.TP
\fB10
\fBCryptographic error.\fR Error may be generated due to untrusted or unavailable hash algorithm or by an invalid PKI signature or untrusted certificate.
.\"
.TP
\fB11
\fBHMAC error.\fR HMAC of aggregation or extend response does not match.
.\"
.TP
\fB12
\fBNo privileges.\fR Operating system did not grant privileges to perform an operation.
.\"
.TP
\fB13
\fBSystem out of memory.\fR
.\"
.TP
\fB14
\fBAuthentication error.\fR Aggregation or extending service did not accept user identification parameters.
.br
.\"
.TP
\fB16
\fBInvalid configuration.\fR KSI tool configuration or KSI C API library configuration is invalid.
.br
.\"
.\"
.\"


.SH ENVIRONMENT	

To define default service info environment variables \fBKSI_CONF \fRmust be specified that contains path to KSI configurations file (see \fBksi-conf\fR(5)). Print ksi help (\fB-h\fR) to check if default service info is available.


.SH AUTHOR

Guardtime AS, http://www.guardtime.com/

.SH SEE ALSO	
\fBksi-sign\fR(1), \fBksi-verify\fR(1), \fBksi-extend\fR(1), \fBksi-pubfile\fR(1), \fBksi-conf\fR(5) 